#!/bin/bash

if [ $# -eq 0 ]
  then
    echo "No arguments supplied"
    exit 1
fi

cp AIQuim.cc AIQuim-$1.cc
sed -i '' -- 's/\#define IS_DEBUG 1/\#define IS_DEBUG 0/g' AIQuim-$1.cc
sed -i '' -- "s/\#define PLAYER_NAME Quim/\#define PLAYER_NAME Quim_$1/g" AIQuim-$1.cc